# Generated by Django 4.2.16 on 2024-10-26 09:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListingTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('images', models.JSONField(default=dict, null=True)),
                ('price', models.IntegerField(default=50)),
                ('shipping_charges', models.IntegerField(default=50)),
                ('sample_link', models.URLField(default=None, null=True)),
                ('video_url', models.URLField(default=None, null=True)),
                ('wright', models.FloatField(default=0.5)),
                ('dimensions', models.CharField(default=None, max_length=1000, null=True)),
                ('listing_tags', models.ManyToManyField(related_name='tags', to='core.listingtag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
