# Generated by Django 4.2.16 on 2024-10-27 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_listing_is_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='wright',
            new_name='weight',
        ),
    ]
