# Generated by Django 4.2.16 on 2024-10-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_listingcategory_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='default_color',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
