# Generated by Django 4.2.16 on 2024-12-06 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_listing_default_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='default_color',
        ),
    ]
